#!/bin/bash

g="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
y='\033[1;93m'
gg='\e[1;77m'
ungu="\033[0;35m"
clear
touch /root/.system
echo -e "\e[33m──────────────────────────────────────────${NC}"
echo -e "\E[40;1;37m              USER LOGIN SSH              ${NC}";
echo -e "\e[33m──────────────────────────────────────────${NC}"
echo -e "\E[40;1;37m    LOGIN IP   |  LIMIT IP  |  USERNAME   ${NC}";
echo -e "\e[33m──────────────────────────────────────────${NC}"
mulog=$(mulogssh)
data=( `cat /etc/passwd | grep home | cut -d ' ' -f 1 | cut -d : -f 1`);
for user in "${data[@]}"
do
cekcek=$(echo -e "$mulog" | grep $user | wc -l)
if [[ $cekcek -gt 0 ]]; then
iplimit=$(cat /etc/kyt/limit/ssh/ip/$user)
printf "  %-13s %-7s %-8s %2s\n" "   ${cekcek} IP          ${iplimit} IP        ${user}"
echo "slot" >> /root/.system
else
echo > /dev/null
fi
echo send_log > /dev/null
sleep 0.1
done
aktif=$(cat /root/.system | wc -l)
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo "Total Login SSHWS : $aktif User"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
sed -i "d" /root/.system
echo ""
read -n 1 -s -r -p "Press Any Key To Back"
m-sshws