#!/bin/bash
# https://t.me/gemilangkinasih

CHATID=$(cat /root/telebotvpn/idteleowner)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
IP=$(cat /etc/xray/ipvps)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
  
read -p "Username Info : " user

if ! grep -qiw "$user" /etc/xray/config.json; then
    echo -e "Username tidak ada."
    exit 0
fi

exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
uuid=$(grep -w "^#! $user $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"id":/ {print $4}' | sort | uniq)

sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
sed -i "/^#! $user/d" /etc/trojan/.trojan.db
rm -rf /etc/trojan/$user
rm -rf /etc/kyt/limit/trojan/ip/$user
rm -r /var/www/html/trojan-Trial-"$user".txt > /dev/null 2>&1
rm -r /var/www/html/trojan-"$user".txt > /dev/null 2>&1
systemctl restart xray > /dev/null 2>&1

TEXT="
──────────────────────
Delete Account TROJAN Success
──────────────────────
<code>✧ Host  :</code> <code>$domain</code>
<code>✧ User  :</code> <code>$user</code>
<code>✧ Exp   :</code> <code>$exp</code>
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
# echo "autobackupbot" | at now + 0 minutes &> /dev/null

echo -e "$user"
echo -e "$exp"