#!/bin/bash
# https://t.me/gemilangkinasih


RED="\033[31m"
GREEN='\033[0;32m'
CYAN="\033[36m"
NC="\033[0m"

rm -rf /root/dropbear.sh

if [ "${EUID}" -ne 0 ]; then
    echo -e "${RED}You need to run this script as root!${NC}"
    exit 1
fi

clear

function install_dropbear() {
    clear
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "\033[1;37m    • INSTALL DROPBEAR 2018 •       \033[0m"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    sleep 0.5
    echo -e "${GREEN}[Info]${NC} Removing Existing Dropbear Versions..."
    sudo apt-get remove -y dropbear > /dev/null 2>&1
    sudo apt remove --purge -y dropbear > /dev/null 2>&1
    sudo apt autoremove -y > /dev/null 2>&1
    sleep 0.5
    echo -e "${GREEN}[Info]${NC} Installing Default Dropbear Packages..."
    sudo apt install -y dropbear > /dev/null 2>&1
    sleep 0.5
    echo -e "${GREEN}[Info]${NC} Downloading Dropbear 2018 Sources..."
    wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2018.76.tar.bz2 > /dev/null 2>&1
    sleep 0.5
    echo -e "${GREEN}[Info]${NC} Extracting the sources..."
    tar xvjf dropbear-2018.76.tar.bz2 > /dev/null 2>&1
    cd dropbear-2018.76
    sleep 0.5
    echo -e "${GREEN}[Info]${NC} Building Dropbear..."
    ./configure > /dev/null 2>&1
    make > /dev/null 2>&1
    sudo make install > /dev/null 2>&1
    sleep 0.5
    echo -e "${GREEN}[Info]${NC} Replacing Old Dropbear Binary..."
    sudo rm -f /usr/sbin/dropbear
    sudo cp /usr/local/sbin/dropbear /usr/sbin/dropbear
    sleep 0.5
    echo -e "${GREEN}[Info]${NC} Downloading Dropbear Configuration..."
    wget -q -O /etc/default/dropbear https://raw.githubusercontent.com/adipatixyz/sogokpetek/main/config/dropbear.conf
    chmod +x /etc/default/dropbear
    sleep 0.5
    rm -rf /root/dropbear-2018.76
    rm -rf /root/dropbear-2018.76.tar.bz2
    echo -e "${GREEN}[Info]${NC} Restarting Dropbear services..."
    sudo /etc/init.d/dropbear restart > /dev/null 2>&1
    sleep 1
    clear
    echo ""
    echo -e "${GREEN}[Info]${NC} Dropbear 2018 Successfully Installed and Running!"
    echo ""
    read -p "Press any key to exit..."
    exit 0
}

echo -e "${CYAN}Do you want to install Dropbear 2018? (y/n): ${NC}"
read -rp "Enter your choice: " choice

if [[ "$choice" == "y" || "$choice" == "Y" ]]; then
    install_dropbear
else

    clear
    echo ""
    echo -e "${RED}[Info]${NC} Installation Cancelled."
    echo ""
    read -p "Press any key to exit..."
    exit 0
fi