#!/bin/bash
# https://t.me/gemilangkinasih

function send_log() {
DOMAIN_PART=$(cut -d '.' -f1 /etc/xray/domain | tr '[:lower:]' '[:upper:]')
FULL_DOMAIN=$(cat /etc/xray/domain)

# Cek apakah DOMAIN mengandung "SG"
if [[ "$DOMAIN_PART" == *"SG"* ]]; then
    FLAG="🇸🇬"
else
    FLAG="🇮🇩"
fi

# Konfigurasi informasi Telegram
# CHATID="@tokovpngrub"
CHATID=$(cat /root/telebotvpn/idtelegrub)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIMEOUT="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
──────────────────────
🚫 <b>Notifikasi Multilogin VLESS</b>
──────────────────────
<blockquote><code>SERVER $DOMAIN_PART $FLAG</code></blockquote>
<code>User  :</code> <code>$akun</code>
<code>Login :</code> <code>$jum2 IP</code>
<code>Limit :</code> <code>$((MAX - 1)) IP</code>
────────────────────── 
Notif "$jumx"X Multilogin: 3X Autolock
────────────────────── "

# Kirim pesan ke Telegram
# curl -s --max-time "$TIMEOUT" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=HTML&reply_to_message_id=2485" "$URL" >/dev/null
curl -s --max-time "$TIMEOUT" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function send_logx() {
DOMAIN_PART=$(cut -d '.' -f1 /etc/xray/domain | tr '[:lower:]' '[:upper:]')
FULL_DOMAIN=$(cat /etc/xray/domain)

# Cek apakah DOMAIN mengandung "SG"
if [[ "$DOMAIN_PART" == *"SG"* ]]; then
    FLAG="🇸🇬"
else
    FLAG="🇮🇩"
fi

# Konfigurasi informasi Telegram
# CHATID="@tokovpngrub"
CHATID=$(cat /root/telebotvpn/idtelegrub)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIMEOUT="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
──────────────────────
🚫 <b>Notifikasi Multilogin VLESS</b>
──────────────────────
<blockquote><code>SERVER $DOMAIN_PART $FLAG</code></blockquote>
<code>User  :</code> <code>$akun</code>
<code>Login :</code> <code>$jum2 IP</code>
<code>Limit :</code> <code>$((MAX - 1)) IP</code>
────────────────────── 
Notif 3X Multilogin: Lock 15 Menit
────────────────────── "

# Kirim pesan ke Telegram
# curl -s --max-time "$TIMEOUT" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=HTML&reply_to_message_id=2485" "$URL" >/dev/null
curl -s --max-time "$TIMEOUT" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function send_logxx() {
DOMAIN_PART=$(cut -d '.' -f1 /etc/xray/domain | tr '[:lower:]' '[:upper:]')
FULL_DOMAIN=$(cat /etc/xray/domain)

# Cek apakah DOMAIN mengandung "SG"
if [[ "$DOMAIN_PART" == *"SG"* ]]; then
    FLAG="🇸🇬"
else
    FLAG="🇮🇩"
fi

# Konfigurasi informasi Telegram
# CHATID="@tokovpngrub"
CHATID=$(cat /root/telebotvpn/idtelegrub)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIMEOUT="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
──────────────────────
🚫 <b>Notifikasi Multilogin VLESS</b>
──────────────────────
<blockquote><code>SERVER $DOMAIN_PART $FLAG</code></blockquote>
<code>User  :</code> <code>$akun</code>
<code>Login :</code> <code>$jum2 IP</code>
<code>Limit :</code> <code>$((MAX - 1)) IP</code>
────────────────────── 
Notif 4X Multilogin: Chat Admin
────────────────────── "

# Kirim pesan ke Telegram
# curl -s --max-time "$TIMEOUT" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=HTML&reply_to_message_id=2485" "$URL" >/dev/null
curl -s --max-time "$TIMEOUT" -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

data=( `cat /etc/xray/config.json | grep '#&' | cut -d ' ' -f 2 | sort | uniq`)

# Read log data once and process it
log_data=$(cat /var/log/xray/access.log | tail -n 500)
ip_data=($(echo "$log_data" | grep email | grep "accepted" | awk -F "from " '{print $2}' | sed 's/tcp://g' | sed 's/\[.*//g' | cut -d: -f1 | sort | uniq))
status=0

# Loop through each user
for akun in "${data[@]}"; do
    echo -n > /tmp/ipvlessx.txt
    for ip in "${ip_data[@]}"; do
        # Extract the first two segments of the IP
        # ip_prefiks=$(echo "$ip" | cut -d "." -f1,2)
        ip_prefiks="$ip"

        # Check if this IP belongs to the current user (only need to search through the preloaded log data)
        # jum=$(echo "$log_data" | grep -w "$akun" | grep -w "$ip_prefiks" | grep "accepted" | awk -F "from " '{print $2}' | sed 's/tcp://g' | cut -d ":" -f1 | cut -d "." -f1,2 | sort | uniq)
        jum=$(echo "$log_data" | grep -w "$akun" | grep -w "$ip_prefiks" | grep "accepted" | awk -F "from " '{print $2}' | sed 's/tcp://g' | cut -d ":" -f1 | sort | uniq)
        if [[ "$jum" == "$ip_prefiks" ]]; then
            echo "$jum" >> /tmp/ipvlessx.txt
        fi
    done
    
    jum=$(cat /tmp/ipvlessx.txt)
    if [[ -n "$jum" ]]; then
        if [ -e "/etc/kyt/limit/vless/ip/${akun}" ]; then
            iplimit=$(cat /etc/kyt/limit/vless/ip/${akun})
            MAX=$((iplimit + 1))
        else
            MAX=2
            echo "2" > /etc/kyt/limit/vless/ip/${akun}
        fi

        if [ "$MAX" -eq 0 ]; then
            MAX=2
            echo "2" > /etc/kyt/limit/vless/ip/${akun}
        fi
        jum2=$(sort /tmp/ipvlessx.txt | uniq | wc -l)
        echo "Memproses User : [Login: $jum2, Limit: $((MAX - 1))] $akun"
        # Check if the number of logged-in IPs exceeds the limit
        if [ "$jum2" -gt "$MAX" ]; then
            exp=$(grep -w "^#& $akun" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            uuid=$(grep -w "^#& $akun $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"id":/ {print $4}' | sort | uniq)
            if [[ -z $exp || -z $uuid ]]; then
                continue  # Skip if exp or uuid is empty
            fi

            echo "$akun" >> /tmp/lockipxray.txt
        
            if [[ $(grep -c "$akun" /tmp/lockipxray.txt) -gt 3 ]]; then
exp=$(grep -wE "^#& $akun" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
uuid=$(grep -w "^#& $akun $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"id":/ {print $4}' | sort | uniq)
uuid2=$(grep -w "^#& $akun $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"id":/ {print $4}' | sed 's/.*\(LOCKED\)/\1/' | sort | uniq)

if [[ "$uuid2" == "LOCKED" ]]; then
    echo -e "Account $akun has been locked, melewati proses."
    continue
fi

status=1

echo "Locked user $akun 4X Multilogin"
sed -i "/^#& $akun $exp/,/^},{/d" /etc/xray/config.json
sed -i "/^### $akun/d" /etc/vless/.vless.db
sed -i '/#vless$/a\#& '"$akun $exp"'\
},{"id": "'""$uuid"LOCKED"'","email" : "'""$akun""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$akun $exp"'\
},{"id": "'""$uuid"LOCKED"'","email" : "'""$akun""'"' /etc/xray/config.json
truncate -s 0 /var/log/xray/access.log
sed -i "/$akun/d" /tmp/lockipxray.txt
send_logxx "$akun" "$jum2" "$((MAX - 1))"
                continue
            fi
            
            if [[ $(grep -c "$akun" /tmp/lockipxray.txt) -gt 2 ]]; then
exp=$(grep -wE "^#& $akun" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
uuid=$(grep -w "^#& $akun $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"id":/ {print $4}' | sort | uniq)
uuid2=$(grep -w "^#& $akun $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"id":/ {print $4}' | sed 's/.*\(LOCKED\)/\1/' | sort | uniq)

if [[ "$uuid2" == "LOCKED" ]]; then
    echo -e "Account $akun has been locked, melewati proses."
    continue
fi

status=1

echo "Unlock user $akun dalam 15 menit."
echo "unlocklimitip vless $akun $exp $uuid" | at now + 15 minutes &> /dev/null
sed -i "/^#& $akun $exp/,/^},{/d" /etc/xray/config.json
sed -i "/^### $akun/d" /etc/vless/.vless.db
sed -i '/#vless$/a\#& '"$akun $exp"'\
},{"id": "'""$uuid"LOCKED"'","email" : "'""$akun""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$akun $exp"'\
},{"id": "'""$uuid"LOCKED"'","email" : "'""$akun""'"' /etc/xray/config.json
truncate -s 0 /var/log/xray/access.log
send_logx "$akun" "$jum2" "$((MAX - 1))"
                continue
            fi

echo "User $akun melebihi batas login, send notif!"
truncate -s 0 /var/log/xray/access.log
jumx=$(grep -c "$akun" /tmp/lockipxray.txt)
send_log "$akun" "$jum2" "$((MAX - 1))" "$jumx"
        fi
    fi 
    rm -rf /tmp/ipvlessx.txt
    sleep 3
done

if [[ "$status" -eq 1 ]]; then
    echo "Terjadi pelanggaran multilogin, restart layanan xray."
    systemctl restart xray > /dev/null 2>&1
fi
rm -rf /tmp/ipvlessx.txt
echo "Siklus monitoring selesai. sleep 300 detik!"
sleep 300