#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Developers » Gemilangkinasih࿐
# Email      » gemilangpremium@gmail.com
# Telegram   » https://t.me/gemilangkinasih
# WhatsApp   » wa.me/+6287782718065
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐

function send_log() {
domain=$(cat /etc/xray/domain)
CHATID=$(cat /root/telebotvpn/idtelegrub)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
──────────────────────
🚫 Notifikasi Multilogin TROJAN
──────────────────────
<code>User  :</code> <code>$user</code>
<code>Login :</code> <code>$cekcek</code>
<code>Limit :</code> <code>$iplimit</code>
<code>Host  :</code> <code>$domain</code>
────────────────────── 
Unlock User Otomatis 15 Menit
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

data=(`cat /etc/xray/config.json | grep '#!' | cut -d ' ' -f 2 | sort | uniq`)
# Loop through each user
for akun in "${data[@]}"; do
    echo -n > /tmp/iptrojan.txt
    data2=(`cat /var/log/xray/access.log | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq`)
    
    # Loop through each IP address and check for usage
    for ip in "${data2[@]}"; do
        jum=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | grep -w "$ip" | sort | uniq)
        if [[ "$jum" == "$ip" ]]; then
            echo "$jum" >> /tmp/iptrojan.txt
        fi
    done
    
    jum=$(cat /tmp/iptrojan.txt)
    if [[ -n "$jum" ]]; then
        iplimit=$(cat /etc/kyt/limit/trojan/ip/${akun})
        jum2=$(sort /tmp/iptrojan.txt | uniq | wc -l)
        echo "Memproses User : [Login: $jum2, Limit: $iplimit] $akun"
        # Check if the number of logged-in IPs exceeds the limit
        if [ "$jum2" -gt "$iplimit" ]; then
            exp=$(grep -w "^#! $akun" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
            uuid=$(grep -w "^#! $akun $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"password":/ {print $4}' | sort | uniq)
            if [[ -z $exp || -z $uuid ]]; then
                continue  # Skip if exp or uuid is empty
            fi
            echo "Unlock user $akun dalam 15 menit."
            echo "unlocklimitip trojan $akun $exp $uuid" | at now + 15 minutes &> /dev/null
            sed -i "/^#! $akun $exp/,/^},{/d" /etc/xray/config.json
            systemctl restart xray
            send_log "$akun" "$jum2" "$iplimit"  # Kirim log jika ada
        fi
    fi 
    rm -rf /tmp/iptrojan.txt
    sleep 5
done
sleep 10

# Cleanup
rm -rf /tmp/iptrojan.txt