#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangpremium@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+6287782718065
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐

function send_log(){
domain=$(cat /etc/xray/domain)
CHATID=$(cat /root/telebotvpn/idtelegrub)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
──────────────────────
🚫 Notifikasi Multilogin TROJAN
──────────────────────
<code>User  :</code> <code>$user</code>
<code>Limit :</code> <code>$iplimit</code>
<code>Login :</code> <code>$cekcek</code>
<code>Domen :</code> <code>$domain</code>
────────────────────── 
Unlock User Otomatis 15 Menit
────────────────────── "
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

echo -n > /var/log/xray/access.log
sleep 5
data=( `ls /etc/kyt/limit/trojan/ip`);
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/trojan/ip/$user)
        # iplimit=3
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
uuid=$(grep -w "^#! $user $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"password":/ {print $4}' | sort | uniq)
if [[ -z $exp || -z $uuid ]]; then
echo "User $user has an empty expiration or UUID."
sleep 5
continue
fi
echo "unlocklimitipbot trojan $user $exp $uuid" | at now + 15 minutes &> /dev/null
sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
systemctl restart xray
send_log "$user" "$iplimit" "$cekcek"
echo "Locked $user and Send Notif Telebot Success."
            else
            sleep 5
        fi
        sleep 5
    done
sleep 30