#!/bin/bash
# https://t.me/gemilangkinasih

clear
# Fungsi untuk mengirim notifikasi ke Telegram
function send-log() {
domain=$(cat /etc/xray/domain)
CHATID=$(cat /root/telebotvpn/idtelegrub)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
──────────────────────
🚫 Notifikasi Multilogin SSH
──────────────────────
<code>User  :</code> <code>$1</code>
<code>Login :</code> <code>$2 IP</code>
<code>Limit :</code> <code>$3 IP</code>
<code>Host  :</code> <code>$domain</code>
────────────────────── 
Unlock User Otomatis 15 Menit
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function send-logx() {
domain=$(cat /etc/xray/domain)
CHATID=$(cat /root/telebotvpn/idtelegrub)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
──────────────────────
🚫 Notifikasi Multilogin SSH
──────────────────────
<code>User  :</code> <code>$1</code>
<code>Login :</code> <code>$2 IP</code>
<code>Limit :</code> <code>$3 IP</code>
<code>Host  :</code> <code>$domain</code>
────────────────────── 
Delete User 10X Multilogin
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

# Mendapatkan daftar pengguna yang terdaftar di /home/
echo "Memulai proses monitoring pengguna SSH..."
cat /etc/passwd | grep "/home/" | cut -d":" -f1 > /root/user.txt

# Membaca daftar pengguna ke dalam array
user=( $(cat /root/user.txt) )

# Membaca log aktivitas login
mulog=$(mulogssh)

for user in "${user[@]}"; do
    cekcek=$(echo -e "$mulog" | grep -w "$user" | wc -l)

    if [[ $cekcek -gt 0 ]]; then
        # Mengecek batas login per pengguna
        if [ -e "/etc/kyt/limit/ssh/ip/$user" ]; then
            LIMIT=$(cat /etc/kyt/limit/ssh/ip/$user)
            MAX=$((LIMIT + 1))
        else
            MAX=2
            echo "2" > /etc/kyt/limit/ssh/ip/$user
        fi

        if [ "$MAX" -eq 0 ]; then
            MAX=2
            echo "2" > /etc/kyt/limit/ssh/ip/$user
        fi

        # Mengecek status pengguna (terkunci atau tidak)
        STATUS=$(passwd -S "$user" | awk '{print $2}')
        if [[ "$STATUS" == "L" ]]; then
            echo "User $user terkunci, melewati proses."
            continue
        fi

        # Menampilkan informasi login pengguna
        printf "%-15s %2s %-15s %2s \n" "$user" "[Login: $cekcek IP]" "[Limit: $((MAX - 1)) IP]"
        echo "slot" >> /root/.system

        # Memeriksa apakah pengguna melebihi batas login
        if [[ $cekcek -gt $MAX ]]; then

            if [[ $(grep -c "$user" /root/userlock.txt) -ge 10 ]]; then
                echo "Menghapus pengguna $user karena sudah terlock lebih dari 10 kali."
                userdel "$user"
                sed -i "/$user/d" /root/userlock.txt
                send-logx "$user" "$cekcek" "$((MAX - 1))"
                echo "Notifikasi terkirim ke Telegram."
            fi

            echo "User $user melebihi batas login, mengunci akun."
            passwd -l "$user"
            echo "unlocklimitipbot ssh $user" | at now + 15 minutes &>/dev/null
            echo "$user" >> /root/userlock.txt
            send-log "$user" "$cekcek" "$((MAX - 1))"
            echo "Notifikasi terkirim ke Telegram."

            if [[ $cekcek -gt 5 ]]; then
                truncate -s 0 /var/log/auth.log
                systemctl restart ssh > /dev/null 2>&1;
                systemctl restart sshd > /dev/null 2>&1;
                # systemctl restart ws > /dev/null 2>&1;
            fi

        fi
    fi
    sleep 0.5
done
# Menghitung jumlah pengguna yang aktif
aktif=$(wc -l < /root/.system)
echo "Total Login SSHWS : $aktif User"
rm -f /root/.system
echo "Siklus monitoring selesai. Menunggu 30 detik sebelum memulai ulang."
sleep 30
