#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangpremium@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+6287782718065
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐

function send-log(){
domain=$(cat /etc/xray/domain)
CHATID=$(cat /root/telebotvpn/idtelegrub)
KEY=$(cat /root/telebotvpn/tokentelebot)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
──────────────────────
🚫 Notifikasi Limit Quota VMESS
──────────────────────
<code>User  :</code> <code>$user</code>
<code>Limit :</code> <code>$total2</code>
<code>Usage :</code> <code>$total</code>
<code>Domen :</code> <code>$domain</code>
────────────────────── 
Buy Tambah Quota Untuk Unlock
────────────────────── "

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function con() {
    local -i bytes=$1;
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes} B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 )) KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 )) MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 )) GB"
    fi
}

  while true; do
  sleep 30
  data=($(cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
  if [[ ! -e /etc/limit/vmess ]]; then
  mkdir -p /etc/limit/vmess
  fi
  for user in ${data[@]}
  do
  xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" >& /tmp/${user}
  getThis=$(cat /tmp/${user} | awk '{print $1}');
  if [[ ${getThis} != "failed" ]]; then
        downlink=$(xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" | grep -w "value" | awk '{print $2}' | cut -d '"' -f2);
        if [ -e /etc/limit/vmess/${user} ]; then
        plus2=$(cat /etc/limit/vmess/${user});
        if [[ ${#plus2} -gt 0 ]]; then
        plus3=$(( ${downlink} + ${plus2} ));
        echo "${plus3}" > /etc/limit/vmess/"${user}"
        xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        else
        echo "${downlink}" > /etc/limit/vmess/"${user}"
        xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
        else
        echo "${downlink}" > /etc/limit/vmess/"${user}"
        xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
        fi
        else
      echo ""
   fi
done
for user in ${data[@]}
  do
    if [[ -f /etc/vmess/${user} ]]; then
        checkLimit=$(cat /etc/vmess/${user})
    else
        checkLimit=536870912000
        echo "536870912000" > /etc/vmess/${user}
    fi

    if [[ "$checkLimit" -eq 0 ]]; then
        checkLimit=536870912000
        echo "536870912000" > /etc/vmess/${user}
    fi

    if [ -e /etc/vmess/${user} ]; then
      checkLimit=$(cat /etc/vmess/${user});
      if [[ ${#checkLimit} -gt 1 ]]; then
      if [ -e /etc/limit/vmess/${user} ]; then
      Usage=$(cat /etc/limit/vmess/${user});
      total=$(con ${Usage})
      total2=$(con ${checkLimit})
      if [[ ${Usage} -gt ${checkLimit} ]]; then
exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
uuid=$(grep -w "^### $user $exp" -A 1 "/etc/xray/config.json" | awk -F'"' '/"id":/ {print $4}' | sort | uniq)
if [[ -z $exp || -z $uuid ]]; then
echo "User $user has an empty expiration or UUID. Restarting the system."
systemctl restart xray
sleep 5
continue
fi
echo "### $user $exp $uuid" >> /usr/local/sbin/limitxray
sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
echo "0" > "/etc/limit/vmess/${user}"
send-log
systemctl restart xray
sleep 15
      else
      sleep 1
      fi
      else
      sleep 1
      fi
      else
      sleep 1
      fi
      else
      sleep 1
    fi
  done
done
sleep 30