#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangpremium@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+6287782718065
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐
  
read -p "Username Info : " user
read -p "Expired Day   : " masaaktif

if ! grep -qiw "$user" /etc/xray/config.json; then
    echo -e "Username tidak ada."
    exit 0
fi

exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
echo "0" > "/etc/limit/vmess/${user}"
now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(( (d1 - d2) / 86400 ))
exp3=$(($exp2 + $masaaktif))
exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
sed -i "/### $user/c\### $user $exp4" /etc/xray/config.json
sed -i "/### $user/c\### $user $exp4" /etc/vmess/.vmess.db
systemctl restart xray > /dev/null 2>&1

echo -e "$user"
echo -e "$masaaktif Days"
echo -e "$exp"
echo -e "$exp4"