#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangpremium@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+6287782718065
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐
  
read -p "Username Info : " user
read -p "Expired Day   : " masaaktif

if ! grep -qiw "$user" /etc/xray/config.json; then
    echo -e "Username tidak ada."
    exit 0
fi

Quota=500
iplim=2 
rm -f /etc/kyt/limit/trojan/ip/${user}
# rm -f /etc/trojan/$user
exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
mkdir -p /etc/kyt/limit/trojan/ip
echo "${iplim}" > /etc/kyt/limit/trojan/ip/${user}
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(( (d1 - d2) / 86400 ))
exp3=$(($exp2 + $masaaktif))
exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
sed -i "/#! $user/c\#! $user $exp4" /etc/xray/config.json
sed -i "/#! $user/c\#! $user $exp4" /etc/trojan/.trojan.db
systemctl restart xray > /dev/null 2>&1

echo -e "$user"
echo -e "$masaaktif Days"
echo -e "$exp"
echo -e "$exp4"