#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangpremium@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+6287782718065
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐

user="$2"
function ssh(){
    userdel $user > /dev/null 2>&1
    sed -i "/^#&# $user/d" /etc/ssh/.ssh.db
    rm -r /var/www/html/ssh-Trial-"$user".txt > /dev/null 2>&1
    rm -r /var/www/html/ssh-"$user".txt > /dev/null 2>&1
    systemctl restart ssh >/dev/null 2>&1
	systemctl restart sshd >/dev/null 2>&1
}
function vmess(){
    exp=$(grep -wE "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^#&# $user/d" /etc/vmess/.vmess.db
    rm -rf /etc/vmess/$user
    rm -rf /etc/kyt/limit/vmess/ip/$user
    rm -r /var/www/html/vmess-Trial-"$user".txt > /dev/null 2>&1
    rm -r /var/www/html/vmess-"$user".txt > /dev/null 2>&1
	systemctl restart xray > /dev/null 2>&1
}
function vless(){
    exp=$(grep -wE "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^#&# $user/d" /etc/vless/.vless.db
    rm -rf /etc/vless/$user
    rm -rf /etc/kyt/limit/vless/ip/$user
    rm -r /var/www/html/vless-Trial-"$user".txt > /dev/null 2>&1
    rm -r /var/www/html/vless-"$user".txt > /dev/null 2>&1
    systemctl restart xray > /dev/null 2>&1
}
function trojan(){
    exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
    sed -i "/^#&# $user/d" /etc/trojan/.trojan.db
    rm -rf /etc/trojan/$user
    rm -rf /etc/kyt/limit/trojan/ip/$user
    rm -r /var/www/html/trojan-Trial-"$user".txt > /dev/null 2>&1
    rm -r /var/www/html/trojan-"$user".txt > /dev/null 2>&1
    systemctl restart xray > /dev/null 2>&1
}
function ssws(){
    exp=$(grep -wE "^##@ $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
	sed -i "/^##@ $user $exp/,/^},{/d" /etc/shadowsocks/.shadowsocks.db
	sed -i "/^##@ $user $exp/,/^},{/d" /etc/xray/config.json
	sed -i "/^##@ $user $exp/,/^},{/d" /etc/xray/config.json
	rm -f /etc/shadowsocks/quota-asli/$user
	rm -f /etc/shadowsocks/quota-hasil/$user
	rm -f /etc/shadowsocks/limit/$user
}
if [[ ${1} == "vmess" ]]; then
vmess
elif [[ ${1} == "vless" ]]; then
vless
elif [[ ${1} == "trojan" ]]; then
trojan
elif [[ ${1} == "ssh" ]]; then
ssh
elif [[ ${1} == "ssws" ]]; then
ssws
fi