#!/bin/bash

LIMITXRAY_FILE="/usr/local/sbin/limitxray"

# Periksa apakah file ada
if [[ ! -f "$LIMITXRAY_FILE" ]]; then
    echo "File $LIMITXRAY_FILE tidak ditemukan."
    exit 1
fi

# Menampilkan daftar nama dari file
echo "Daftar Pengguna:"
declare -A user_map
i=1

while IFS= read -r line; do
    # Ekstrak nama pengguna dari format file
    protocol=$(echo "$line" | grep -oE '^###|^#!|^#&')
    name=$(echo "$line" | awk '{print $2}')
    exp=$(echo "$line" | awk '{print $3}')
    case "$protocol" in
        "###")
            proto="[VMESS]"
            ;;
        "#&")
            proto="[VLESS]"
            ;;
        "#!")
            proto="[TROJAN]"
            ;;
        *)
            proto="[Unknown]"
            ;;
    esac
    echo "$i. $proto $name $exp"
    user_map["$i"]="$line"
    ((i++))
done < <(grep -E '^###|^#&|^#!' "$LIMITXRAY_FILE")

# Meminta input nomor
read -p "Masukkan nomor pengguna: " number_input

# Validasi input nomor
selected_line="${user_map[$number_input]}"
if [[ -z "$selected_line" ]]; then
    echo "Nomor tidak valid. Silakan coba lagi."
    exit 1
fi

# Ambil data pengguna berdasarkan nomor
protocol=$(echo "$selected_line" | grep -oE '^###|^#&|^#!')
name=$(echo "$selected_line" | awk '{print $2}')
exp=$(echo "$selected_line" | awk '{print $3}')
uuid=$(echo "$selected_line" | awk '{print $4}')

# Tentukan protokol untuk perintah
case "$protocol" in
    "###")
        proto_type="vmess"
        ;;
    "#&")
        proto_type="vless"
        ;;
    "#!")
        proto_type="trojan"
        ;;
    *)
        echo "Protokol tidak dikenali."
        exit 1
        ;;
esac

# Eksekusi perintah
command="unlocklimitipbot $proto_type $name $exp $uuid"
echo "$command" | at now + 0 minutes &> /dev/null

# Hapus data dari file
sed -i "/$(echo "$selected_line" | sed 's/[\/&]/\\&/g')/d" "$LIMITXRAY_FILE"

# Konfirmasi eksekusi
if [[ $? -eq 0 ]]; then
    echo "Perintah berhasil dijadwalkan dan data pengguna $name telah dihapus."
else
    echo "Gagal menjadwalkan perintah atau menghapus data."
fi
