#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# System Request : Debian 9+/Ubuntu 18.04+/20+
# Develovers » Gemilangkinasih࿐
# Email      » gemilangpremium@gmail.com
# telegram   » https://t.me/gemilangkinasih
# whatsapp   » wa.me/+6287782718065
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Gemilangkinasih࿐

clear
echo -e "\e[33m──────────────────────────────────────────\033[0m"
echo -e "\E[40;1;37m      DELETE USER EXPIRED IN PROCESS      \E[0m"
echo -e "\e[33m──────────────────────────────────────────\033[0m"
loading() {
    local delay=0.1
    local length=25
    local count=0
    local max_count=100
    local line=""
    
    while [ $count -lt $max_count ]; do
        ((count++))
        line=$(printf "%0.s|" $(seq 1 $((count % length))))
        printf "\rProcessing %-${length}s %d%%" "$line" "$count"
        sleep $delay
    done
    printf "\n"
}

##----- Auto Remove Vmess
data=($(cat /etc/xray/config.json | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db

        rm -r /etc/vmess/$user
        rm -r /etc/kyt/limit/vmess/ip/$user
        rm -r /var/www/html/vmess-$user.txt > /dev/null 2>&1
        rm -r /etc/limit/vmess/$user > /dev/null 2>&1

        rm -r /etc/kyt/limit/vmess/ip/Trial-* > /dev/null 2>&1
        rm -r /var/www/html/vmess-Trial-* > /dev/null 2>&1
        rm -r /etc/vmess/Trial-* > /dev/null 2>&1
        rm -r /etc/limit/vmess/Trial-* > /dev/null 2>&1
        
    fi
done

#----- Auto Remove Vless
data=($(cat /etc/xray/config.json | grep '^#&' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/vless/.vless.db

        rm -r /etc/vless/$user
        rm -r /etc/kyt/limit/vless/ip/$user
        rm -r /var/www/html/vless-$user.txt > /dev/null 2>&1
        rm -r /etc/limit/vless/$user > /dev/null 2>&1

        rm -r /etc/kyt/limit/vless/ip/Trial-* > /dev/null 2>&1
        rm -r /var/www/html/vless-Trial-* > /dev/null 2>&1
        rm -r /etc/vless/Trial-* > /dev/null 2>&1
        rm -r /etc/limit/vless/Trial-* > /dev/null 2>&1
    fi
done

#----- Auto Remove Trojan
data=($(cat /etc/xray/config.json | grep '^#!' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db

        rm -r /etc/trojan/$user
        rm -r /etc/kyt/limit/trojan/ip/$user
        rm -r /var/www/html/trojan-$user.txt > /dev/null 2>&1
        rm -r /etc/limit/trojan/$user > /dev/null 2>&1

        rm -r /etc/kyt/limit/trojan/ip/Trial-* > /dev/null 2>&1
        rm -r /var/www/html/trojan-Trial-* > /dev/null 2>&1
        rm -r /etc/trojan/Trial-* > /dev/null 2>&1
        rm -r /etc/limit/trojan/Trial-* > /dev/null 2>&1
    fi
done

#----- Auto Remove SS
data=($(cat /etc/xray/config.json | grep '^#!#' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
    exp=$(grep -w "^#!# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(((d1 - d2) / 86400))
    if [[ "$exp2" -le "0" ]]; then
        sed -i "/^#!# $user $exp/,/^},{/d" /etc/xray/config.json
        sed -i "/^#!# $user $exp/,/^},{/d" /etc/xray/config.json
    fi
done
systemctl restart xray

##------ Auto Remove SSH
hariini=$(date +%d-%m-%Y)
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d >/tmp/expirelist.txt
totalaccounts=$(cat /tmp/expirelist.txt | wc -l)
for ((i = 1; i <= $totalaccounts; i++)); do
    tuserval=$(head -n $i /tmp/expirelist.txt | tail -n 1)
    username=$(echo $tuserval | cut -f1 -d:)
    userexp=$(echo $tuserval | cut -f2 -d:)
    userexpireinseconds=$(($userexp * 86400))
    tglexp=$(date -d @$userexpireinseconds)
    tgl=$(echo $tglexp | awk -F" " '{print $3}')
    while [ ${#tgl} -lt 2 ]; do
        tgl="0"$tgl
    done
    while [ ${#username} -lt 15 ]; do
        username=$username" "
    done
    bulantahun=$(echo $tglexp | awk -F" " '{print $2,$6}')
    todaystime=$(date +%s)
    if [ $userexpireinseconds -ge $todaystime ]; then
        :
    else
        userdel $username > /dev/null 2>&1
        sed -i "/^### $username/d" /etc/ssh/.ssh.db
        rm -r /var/www/html/ssh-$username.txt > /dev/null 2>&1

        rm -r /etc/kyt/limit/ssh/ip/Trial-*  > /dev/null 2>&1
    fi
done
systemctl restart ssh

loading

echo -e "Delete User Expired Success"
echo -e "\e[33m──────────────────────────────────────────\033[0m" 
echo -e ""
echo -e "Back to menu on 5 second"
sleep 5
menu